### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jakeburns** [ashstrahle/RealtimePowerShellHTMLWindow#3]
Is there a way to change the method of authentication the project uses (windows authentication) to work with an ldap authentication? @ashstrahle

**Comment by ashstrahle** [comment]
Hi @jakeburns. The only reason this project uses windows authentication is to have unique hubGroup targets to write the output to a user's session. i.e: hubGroup = User.Identity.Name in PowershellController. I see know reason why you couldn't use LDAP authentication instead and use the user's CN as the target hubGroup identity.

**Comment by ashstrahle** [comment]
Just an FYI - I've just recently rewritten this project in .Net 6, available here: [PowerShellPortal](https://github.com/ashstrahle/PowerShellPortal). This project is now deprecated as it's based on .Net Framework 4.8.

**Comment by jakeburns** [comment]
> Hi @jakeburns. The only reason this project uses windows authentication is to have unique hubGroup targets to write the output to a user's session. i.e: hubGroup = User.Identity.Name in PowershellController. I see know reason why you couldn't use LDAP authentication instead and use the user's CN as the target hubGroup identity.

So to modify the project for LDAP I would adjust the hubGroup variable in the controller and also adjust variables in the OutputHub? I need to implement the unique hubGroup targets because when running my application on multiple computers, everyone on every computer sees ALL the output, not just the output from their session. But I need to use LDAP and find a way to get the ldap name in both the controller and hub.

**Comment by ashstrahle** [comment]
Precisely.

**Comment by jakeburns** [comment]
> Precisely.

Are you familiar with LDAP at all? Do you know the best way that I can grab a unique id in both the hub and controller?

**Comment by ashstrahle** [comment]
Certainly, however the solution will depend on your particulars and how the clients authenticate with the .Net app. i.e, What LDAP software? Is there an LDAP client? Samba/Netbios involved? Client OS? 

Nevertheless, as this project is discontinued, please use this project instead: [PowerShellPortal](https://github.com/ashstrahle/PowerShellPortal)

**Comment by jakeburns** [comment]
Have you ever had an issue where the pop up window with the results gets stuck loading for a few seconds and some of the output from the script is missed?

**Comment by ashstrahle** [comment]
Use [PowerShellPortal](https://github.com/ashstrahle/PowerShellPortal). It's more efficient as it's in .Net core. This project is no longer supported.
